CREATE TABLE public.pluggy_conexoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    conta_id BIGINT NOT NULL,
    item_id UUID NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (empresa_id, conta_id),
    UNIQUE (item_id)
);

 

 CREATE TABLE IF NOT EXISTS public.pluggy_cartoes
(
    id                 BIGSERIAL PRIMARY KEY,
    empresa_id         BIGINT NOT NULL,
    conta_id           BIGINT NOT NULL,
    pluggy_item_id     UUID NOT NULL,
    pluggy_cartao_id   UUID NOT NULL,
    numero_cartao      TEXT NOT NULL,
    criado_em          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_pluggy_cartoes
        UNIQUE (empresa_id, pluggy_cartao_id)
);