INSERT INTO "contab"."modelos" (  "codigo", "nome", "ativo", "tipo_automacao") 
VALUES ( 'VENDAS_REFEICAO', 'Venda de Refeição à Vista', 'true', 'FINANCEIRO_PADRAO'),
(  'VENDA_BEBIDA', 'Venda de Bebida à Vista', 'true', 'FINANCEIRO_PADRAO'),
(  'COMPRA_INSUMO_VISTA', 'Compra de Insumo à Vista', 'true', 'FINANCEIRO_PADRAO'), 
(  'COMPRA_INSUMO_PRAZO', 'Compra de Insumo a Prazo', 'true', 'FINANCEIRO_PADRAO'), 
(  'PAG_FORNECEDOR', 'Pagamento de Fornecedor', 'true', 'FINANCEIRO_PADRAO'),
( 'PAG_SALARIOS', 'Pagamento de Salários', 'true', 'FINANCEIRO_PADRAO'),
(  'ADIANT_SALARIO', 'Adiantamento de Salário', 'true', 'FINANCEIRO_PADRAO'),
(  'BAIXA_ADIANT_SALARIO', 'Baixa de Adiantamento de Salário', 'true', 'FINANCEIRO_PADRAO'), 
(  'PAG_BENEFICIOS', 'Pagamento de Benefícios (VT/VR)', 'true', 'FINANCEIRO_PADRAO'), 
(  'RECEB_CARTAO', 'Recebimento via Cartão (com taxa)', 'true', 'FINANCEIRO_PADRAO'), 
(  'PERDA_ESTOQUE', 'Perda de Estoque (avarias/vencimento)', 'true', 'ESTOQUE_PERDA'), 
(  'TRANSFERENCIA_CAIXA_BANCO', 'Transferência entre Caixa e Bancos', 'true', 'FINANCEIRO_PADRAO'),
(  'EMP_EMPRESTIMO', 'Empréstimo Bancário (entrada)', 'true', 'EMPRESTIMO_ENTRADA'), 
(  'PAG_EMPRESTIMO', 'Pagamento de Empréstimo (principal/juros)', 'true', 'EMPRESTIMO_PAGAMENTO'), 
(  'DIST_LUCROS', 'Distribuição de Lucros aos Sócios', 'true', 'FINANCEIRO_PADRAO'), 
(  'APUR_ISS', 'Apuração de ISS sobre Vendas', 'true', 'FINANCEIRO_PADRAO'),
(  'APUR_PISCOFINS', 'Apuração de PIS/COFINS', 'true', 'FINANCEIRO_PADRAO'), 
(  'RECEB_CLIENTE_PRAZO', 'Recebimento de Cliente a Prazo', 'true', 'FINANCEIRO_PADRAO'), 
(  'APORTE_SOCIOS', 'Constituição de Capital (Aporte)', 'true', 'FINANCEIRO_PADRAO'),
(  'VENDAS', 'Receita de vendas', 'true', 'FINANCEIRO_PADRAO'), 
(  'RECEBIMENTO_PIX', 'Recebimento via PIX', 'true', 'FINANCEIRO_PADRAO'), 
(  'RECEBIMENTO_CARTAO', 'Recebimento via cartão', 'true', 'FINANCEIRO_PADRAO'), 
(  'RECEITA_FINANCEIRA', 'Receitas financeiras', 'true', 'FINANCEIRO_PADRAO'),
(  'RECEITA_EXTRA', 'Receitas eventuais', 'true', 'FINANCEIRO_PADRAO'), 
(  'DESPESAS_OPERACIONAIS', 'Despesas operacionais', 'true', 'FINANCEIRO_PADRAO'), 
(  'DESPESAS_MORADIA', 'Moradia', 'true', 'FINANCEIRO_PADRAO'), 
(  'DESPESAS_COMUNICACAO', 'Comunicação', 'true', 'FINANCEIRO_PADRAO'),
(  'DESPESAS_ALIMENTACAO', 'Alimentação', 'true', 'FINANCEIRO_PADRAO'), 
(  'DESPESAS_TRANSPORTE', 'Transporte', 'true', 'FINANCEIRO_PADRAO'),
(  'DESPESAS_SAUDE', 'Saúde', 'true', 'FINANCEIRO_PADRAO'),
(  'DESPESAS_EDUCACAO', 'Educação', 'true', 'FINANCEIRO_PADRAO'), 
(  'DESPESAS_LAZER', 'Lazer', 'true', 'FINANCEIRO_PADRAO'), 
(  'DESPESAS_FINANCEIRAS', 'Despesas financeiras', 'true', 'FINANCEIRO_PADRAO'), 
(  'DESPESAS_TRIBUTARIAS', 'Tributos', 'true', 'FINANCEIRO_PADRAO'),
(  'MARKETING', 'Marketing', 'true', 'FINANCEIRO_PADRAO'),
(  'SOFTWARE', 'Softwares e licenças', 'true', 'FINANCEIRO_PADRAO'),
(  'DIVERSOS', 'Despesas diversas', 'true', 'FINANCEIRO_PADRAO'),
(  'VENDA_REFEICAO', 'Venda de Refeições', 'true', 'FINANCEIRO_PADRAO'), 
(  'COMPRA_CARTAO', 'Compra no cartão de crédito', 'true', 'CARTAO_COMPRA'),
(  'ESTORNO_CARTAO', 'Estorno de compra no cartão', 'true', 'CARTAO_ESTORNO'), 
(  'PROVISAO_FATURA_CARTAO', 'Provisão de fatura do cartão', 'true', 'CARTAO_PROVISAO'), 
(  'PAGAMENTO_FATURA_CARTAO', 'Pagamento da fatura do cartão', 'true', 'CARTAO_PAGAMENTO'),
(  'CRIA_PAGAR', 'Criação de conta a pagar (provisão)', 'true', 'CONTAS_PAGAR'), (  'CRIA_RECEBER', 'Criação de conta a receber (provisão)', 'true', 'CONTAS_RECEBER'),
(  'PAGAR', 'Pagamento de conta a pagar', 'true', 'CONTAS_PAGAR'), (  'RECEBER', 'Recebimento de conta a receber', 'true', 'CONTAS_RECEBER'),
(  'CANCELA_PAGAR', 'Cancelamento de conta a pagar', 'true', 'CONTAS_PAGAR'), ( 'CANCELA_RECEBER', 'Cancelamento de conta a receber', 'true', 'CONTAS_RECEBER'), 
(  'AJUSTE_SALDO_ENTRADA', 'Ajuste de saldo – entrada', 'true', 'FINANCEIRO_PADRAO'), (  'AJUSTE_SALDO_SAIDA', 'Ajuste de saldo – saída', 'true', 'FINANCEIRO_PADRAO'),
(  'COMPRA_ESTOQUE', 'Compra de estoque', 'true', 'ESTOQUE_ENTRADA'), ( 'BAIXA_ESTOQUE', 'Baixa de estoque', 'true', 'ESTOQUE_SAIDA'), 
(  'COMPRA_IMOBILIZADO', 'Compra de ativo imobilizado', 'true', 'IMOBILIZADO_COMPRA'),
(  'DEPRECIACAO_IMOBILIZADO', 'Depreciação de ativo imobilizado', 'true', 'IMOBILIZADO_DEPRECIACAO'), ( 'CUSTO_REFEICAO_VENDA', 'Custo de refeição vendida', 'true', 'financeiro'),
(  'RECEITA_BRUTA', 'RECEITA BRUTA', 'true', 'FINANCEIRO_PADRAO'), (  'IMPOSTO_VENDA', 'IMPOSTO SOBRE VENDAS', 'true', 'FINANCEIRO_PADRAO'), 
(  'BATATA', 'BATATA', 'true', 'FINANCEIRO_PADRAO'),
(  'Custovendido', 'Custovendido', 'true', 'FINANCEIRO_PADRAO'), ( 'CMV', 'CUSTO MERCADORIA VENDIDA', 'true', 'FINANCEIRO_PADRAO'), ( 'CMV$', 'CMV PAGO NO CIXA', 'true', 'FINANCEIRO_PADRAO');